services:
  backend:
    build:
      dockerfile: ./Dockerfile
    image: my-notes-app
    env_file:
      - be.env
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres
    env_file:
      - db.env
    ports:
      - "5432:5432"
  prometheus:
    image: prom/prometheus
    expose:
      - "9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"